name: Create-File-and-Upload-Artifact

on:
  push:
    branches:
      - main

jobs:
  create-file-and-upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Create test file
        run: echo "This is just test file for Steven." > steven-${{ github.sha }}.txt
        shell: bash
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Steven-File
          path: steven-${{ github.sha }}.txt
