name: W2

on:
  push:
    branches:
      - main
env:
  OWNER: PulkitBindal
  REPO: Git_Artifact_Logic
jobs:
  check_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Latest Run and Artifact
        run: |
          latest_run_id=$(curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$OWNER/$REPO/actions/runs | jq -r '.workflow_runs | sort_by(.created_at) | last | .id')
          latest_artifact_id=$(curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$OWNER/$REPO/actions/artifacts | jq -r '.artifacts | sort_by(.created_at) | last | .id')
          latest_artifact_name=$(curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$OWNER/$REPO/actions/artifacts | jq -r '.artifacts | sort_by(.created_at) | last | .name')
      
          if [ -z "$latest_run_id" ]; then
            echo "LatestRunID is empty"
          else
            echo "LatestRunID=$latest_run_id" >> "$GITHUB_ENV"
          fi
          
          if [ -z "$latest_artifact_id" ]; then
            echo "LatestArtifactID is empty"
          else
            echo "LatestArtifactID=$latest_artifact_id" >> "$GITHUB_ENV"
          fi
          
          if [ -z "$latest_artifact_name" ]; then
            echo "LatestArtifactName is empty"
          else
            echo "LatestArtifactName=$latest_artifact_name" >> "$GITHUB_ENV"
          fi
        shell: bash

      - name: Check if artifact exists
        id: check_artifact
        run: |
          if [[ -n "${{ steps.list_artifacts.outputs.LatestName }}" ]]; then
            echo "Hooray! Artifacts found from W1"
            echo "Artifact Name: ${{ steps.list_artifacts.outputs.LatestName }}"
          else
            echo "So Sad! Artifacts is not there"
          fi
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.ARTIFACTLOGIC}}
          workflow: W1.yaml
          if_no_artifact_found: warn
      
      - name: List Files
        run: ls -R
