name: W2

on:
  push:
    branches:
      - main
env:
  OWNER: PulkitBindal
  REPO: Git_Artifact_Logic
jobs:
  job1_list_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Downloading Artifact Details
        id: list_artifacts
        run: |
          latest_artifact_name=$(curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$OWNER/$REPO/actions/artifacts | jq -r '.artifacts | sort_by(.created_at) | last | .name')
          echo "LatestArtifactName=$latest_artifact_name" >> $GITHUB_ENV
          echo "Latest Artifact Name is $latest_artifact_name"
          
          RESPONSE=$(curl -s -H "Accept: application/vnd.github+json" -o /dev/null -w "%{http_code}" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$OWNER/$REPO/actions/artifacts | jq -r '.artifacts | sort_by(.created_at) | last | .name')
          if [ $RESPONSE -eq 200 ]; then
            echo "ARTIFACT_EXISTS=True" >> $GITHUB_ENV
          else
            echo "ARTIFACT_EXISTS=False" >> $GITHUB_ENV
          fi

  job2_check_artifact_name:
    if: env.ARTIFACT_EXISTS == 'True'
    runs-on: ubuntu-latest
    steps:
      - name: Printing
        run: echo "Hooray! Artifacts found"
      - name: Downloading artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.ARTIFACTLOGIC}}
          workflow: W1.yaml
          name: steven
          if_no_artifact_found: warn
      
      - name: List Files
        run: ls -lrt

  # job3_check_artifact_name:
  #   if: {{ env.LatestArtifactName != 'steven'}}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Printing
  #       run: echo "So Sad! Artifacts not found"

  #     - name: Downloading artifact
  #       uses: dawidd6/action-download-artifact@v3
  #       with:
  #         github_token: ${{secrets.ARTIFACTLOGIC}}
  #         workflow: W1.yaml
  #         name: steven
  #         if_no_artifact_found: warn
      
      - name: List Files
        run: ls -lrt
