name: W2

on:
  push:
    branches:
      - main
env:
  OWNER: PulkitBindal
  REPO: GIT_Artifact_Logic
jobs:
  normal_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check Latest Artifact 
        run: |
          #!/bin/bash
          OWNER="PulkitBindal"
          REPO="GIT_Artifact_Logic"
          WORKFLOW="W1.yaml"
          
          latest_run_url=$(curl -s -H "Authorization: Bearer ${{secrets.ARTIFACTLOGIC}}" "https://api.github.com/repos/$OWNER/$REPO/actions/workflows/$WORKFLOW/runs?per_page=1" | jq -r '.workflow_runs[0].url')
          
          if [[ -z "$latest_run_url" ]] ; then
              echo "No runs found for workflow $WORKFLOW"
              exists="false"
              exit 0
          fi
          
          artifacts_url="${latest_run_url}/artifacts"
          artifacts_response=$(curl -s -H "Authorization: Bearer ${{secrets.ARTIFACTLOGIC}}" "$artifacts_url")
          
          if [[ "$(echo "$artifacts_response" | jq '.total_count')" -gt 0 ]] ; then
              latest_artifact_name=$(echo "$artifacts_response" | jq -r '.artifacts[0].name')
              echo "$latest_artifact_name"
              exists="true"
          else
              echo "No artifacts found for the latest run of workflow $WORKFLOW"
              exists="false"
          fi
          
          echo "exists=$exists"

      - name: Printing Results of Previous Artifact
        run: |
         echo "$exists"
         
  conditional_job:
    runs-on: ubuntu-latest
    needs: normal_job
    steps:
      - name: Conditional Step
        if: ${{ $exists != true }}
        run: |
          OWNER="${{ env.OWNER }}"
          REPO="${{ env.REPO }}"
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ARTIFACTLOGIC }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$OWNER/$REPO/actions/workflows/W1.yaml/dispatches -d '{"ref":"main"}'

      - name: Hold
        uses: jakejarvis/wait-action@master
        with:
         time: '20s'

      - name: Check Latest Artifact for the second time
        run: |
          #!/bin/bash
          OWNER="PulkitBindal"
          REPO="GIT_Artifact_Logic"
          WORKFLOW="W1.yaml"
          
          latest_run_url=$(curl -s -H "Authorization: Bearer ${{secrets.ARTIFACTLOGIC}}" "https://api.github.com/repos/$OWNER/$REPO/actions/workflows/$WORKFLOW/runs?per_page=1" | jq -r '.workflow_runs[0].url')
          
          if [[ -z "$latest_run_url" ]] ; then
              echo "No runs found for workflow $WORKFLOW"
              exists="false"
              exit 0
          fi
          
          artifacts_url="${latest_run_url}/artifacts"
          artifacts_response=$(curl -s -H "Authorization: Bearer ${{secrets.ARTIFACTLOGIC}}" "$artifacts_url")
          
          if [[ "$(echo "$artifacts_response" | jq '.total_count')" -gt 0 ]] ; then
              latest_artifact_name=$(echo "$artifacts_response" | jq -r '.artifacts[0].name')
              echo "$latest_artifact_name"
              exists="true"
          else
              echo "No artifacts found for the latest run of workflow $WORKFLOW"
              exists="false"
          fi
          
          echo "exists=$exists"

      - name: Downloading the artifact
        uses: actions/download-artifact@v4
        with:
          name: steven
          github-token: ${{ secrets.ARTIFACTLOGIC }}
          repository: $OWNER/$REPO

      - name: Display structure of downloaded files
        run: ls -lrt
