name: W2

on:
  push:
    branches:
      - main
env:
  OWNER: PulkitBindal
  RNAME: Git_Artifact_Logic
jobs:
  job1_list_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - uses: xSAVIKx/artifact-exists-action@v0
        id: check_coverage_artifact
        with:
          name: 'steven'

      - name: Printing Results
        run: |
         echo "Result=${{steps.check_coverage_artifact.outputs.exists}}" >> $GITHUB_ENV
         
  # conditional_job:
  #   runs-on: ubuntu-latest
  #   if: steps.check_coverage_artifact.outputs.exists == 'false'
  #   steps:
  #     - name: Conditional Step
  #       run: |
  #         curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$OWNER/$RNAME/actions/workflows/W1.yml/dispatches -d '{"ref":"main"}'

  conditional_job:
    runs-on: ubuntu-latest
    needs: job1_list_artifact
    steps:
      - name: Check Coverage Artifact
        uses: xSAVIKx/artifact-exists-action@v0
        id: check_coverage_artifact
        with:
          name: 'steven'
        
      - name: Set exists flag
        run: echo "COVERAGE_EXISTS=${{ steps.check_coverage_artifact.outputs.exists }}" >> $GITHUB_ENV
        
      - name: Conditional Step
        if: ${{ env.COVERAGE_EXISTS != 'true' }}
        run: echo "This job runs because 'exists' is false"

      - name: Conditional Step 2
        run: |
          OWNER="${{ env.OWNER }}"
          RNAME="${{ env.RNAME }}"
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ARTIFACTLOGIC }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$OWNER/$RNAME/actions/workflows/W1.yaml/dispatches -d '{"ref":"main"}'

      - name: Hold
        uses: jakejarvis/wait-action@master
        with:
         time: '15s'

      - name: Check Coverage Artifact
        uses: xSAVIKx/artifact-exists-action@v0
        with:
          name: 'steven'

      - uses: actions/download-artifact@v4
        with:
          name: steven
          github-token: ${{ secrets.ARTIFACTLOGIC }} # token with actions:read permissions on target repo
          repository: $OWNER/$RNAME
          
      - name: Display structure of downloaded files
        run: ls -R
