name: W2

on:
  workflow_run:
    workflows: ["W1"]
    types:
      - completed

jobs:
  check_artifact:
    runs-on: ubuntu-latest
    outputs:
      artifact_exists: ${{ steps.check_artifact.outputs.artifact_exists }}
    steps:
      - name: Check if artifact exists
        id: check_artifact
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const response = await github.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.payload.workflow_run.id
              });
              console.log('Response:', response);
              const artifactExists = response.data.artifacts.some(artifact => artifact.name === 'W1_artifact');
              console.log('Artifact exists:', artifactExists);
              return artifactExists;
            } catch (error) {
              console.error('Error fetching artifacts:', error);
              return false;
            }
  run_if_no_artifact:
    name: Run if no artifact exists
    needs: check_artifact
    runs-on: ubuntu-latest
    if: ${{ needs.check_artifact.outputs.artifact_exists == 'false' }}
    steps:
      - name: Trigger W1.yaml workflow
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const response = await github.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_file: 'W1.yaml'
              });
              console.log('Workflow dispatch response:', response);
            } catch (error) {
              console.error('Error triggering workflow:', error);
            }
  run_for_downloading_artifact:
    name: Run For Deownloading Artifact
    needs: check_artifact
    runs-on: ubuntu-latest
    if: ${{ needs.check_artifact.outputs.artifact_exists == 'false' }}
    steps:
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: W1.yaml
          if_no_artifact_found: warn
      
      - name: List Files
        run: ls -R
