name: W2

on:
  push:
    branches:
      - main
env:
  OWNER: PulkitBindal
  RNAME: GIT_Artifact_Logic
jobs:
  normal_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - uses: xSAVIKx/artifact-exists-action@v0
        id: check_coverage_artifact
        with:
          name: 'steven'

      - name: Printing Results
        run: |
         echo "Result=${{steps.check_coverage_artifact.outputs.exists}}" >> $GITHUB_ENV
         

  conditional_job:
    runs-on: ubuntu-latest
    needs: normal_job
    steps:
      # - name: Check Coverage Artifact
      #   uses: xSAVIKx/artifact-exists-action@v0
      #   id: check_coverage_artifact
      #   with:
      #     name: "steven"
      - name: Checking Logic via Bash Script
        run: |
            WORKFLOW_NAME="W1.yaml"
            exists="False"
            
            # Define API endpoint
            API_ENDPOINT="https://api.github.com/repos/$OWNER/$RNAME/actions/runs"
            
            # Make API request
            response=$(curl -s -H "Authorization: Bearer ${{ secrets.ARTIFACTLOGIC }}" -H "Accept: application/vnd.github.v3+json" "$API_ENDPOINT")
            
            # Check if workflow exists and has created artifacts
            if [[ $(echo "$response" | jq -r --arg WORKFLOW_NAME "$WORKFLOW_NAME" '.workflow_runs[] | select(.name == $WORKFLOW_NAME and .artifacts_count > 0)') ]]; then
                exists="True"
            fi
            
            echo "Artifact logic exists: $exists"
        
      - name: Set exists flag
        run: echo "COVERAGE_EXISTS=${{ steps.check_coverage_artifact.outputs.exists }}" >> $GITHUB_ENV
        
      - name: Conditional Step
        if: ${{ env.COVERAGE_EXISTS != 'true' }}
        run: echo "This job runs because 'exists' is false"

      - name: Workflow Triggering...
        if: ${{ env.COVERAGE_EXISTS == 'true' }}
        run: |
          OWNER="${{ env.OWNER }}"
          RNAME="${{ env.RNAME }}"
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ARTIFACTLOGIC }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$OWNER/$RNAME/actions/workflows/W1.yaml/dispatches -d '{"ref":"main"}'

      - name: Hold
        uses: jakejarvis/wait-action@master
        with:
         time: '15s'

      - name: Check Coverage Artifact
        uses: xSAVIKx/artifact-exists-action@v0
        with:
          name: 'steven'

      - uses: actions/download-artifact@v4
        with:
          name: steven
          github-token: ${{ secrets.ARTIFACTLOGIC }} # token with actions:read permissions on target repo
          repository: $OWNER/$RNAME
          
      - name: Display structure of downloaded files
        run: ls -R
