name: W2

on:
  workflow_run:
    workflows: ["W1"]
    types:
      - completed

jobs:
  check_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Check if artifact exists
        id: check_artifact
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const response = await github.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.payload.workflow_run.id
              });
              console.log('Response:', response);
              const artifactExists = response.data.artifacts.some(artifact => artifact.name === 'W1_artifact');
              console.log('Artifact exists:', artifactExists);
              return artifactExists;
            } catch (error) {
              console.error('Error fetching artifacts:', error);
              return false;
            }
      - name: Run W1.yaml if artifact does not exist
        if: steps.check_artifact.outputs.artifactExists == 'false'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: workflows } = await github.actions.listRepoWorkflows({ owner: context.repo.owner, repo: context.repo.repo });
            const workflow = workflows.find(w => w.path === '.github/workflows/W1.yaml');
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflow.id,
            });
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: W1_artifact
          github-token: ${{ secrets.ARTIFACTLOGIC }}
          repository: GIT_Artifact_Logic
          run-id: ${{ github.run_id }}
