name: W2

on:
  push:
    branches:
      - main
env:
  OWNER: PulkitBindal
  REPO: Git_Artifact_Logic
jobs:
  check_artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: List workflow run artifacts
        id: list_artifacts
        run: |
          RUN_ID=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$OWNER/$REPO/actions/runs?event=push&status=completed&per_page=1" \
            | jq -r '.workflow_runs[0].id')
          ARTIFACTS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$OWNER/$REPO/actions/runs/$RUN_ID/artifacts")
          echo "artifact=$ARTIFACTS" >> $GITHUB_OUTPUT

      - name: Check if artifact exists
        run: |
          if echo "${{ steps.list_artifacts.outputs.artifact }}" | jq -e '.artifacts[] | select(.name == "W1_artifact")' >/dev/null; then
            echo "Hooray! Artifacts found from W1"
          else
            echo "So Sad! Artifacts is not there"
          fi
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: W1.yaml
          if_no_artifact_found: warn
      
      - name: List Files
        run: ls -R
