name: W2

on:
  workflow_run:
    workflows: ["W1"]
    types:
      - completed

jobs:
  check_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Check if artifact exists
        id: check_artifact
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const response = await github.actions.listWorkflowRunArtifacts({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: context.payload.workflow_run.id
              });
              console.log('Response:', response);
              const artifactExists = response.data.artifacts.some(artifact => artifact.name === 'W1_artifact');
              console.log('Artifact exists:', artifactExists);
              return artifactExists;
            } catch (error) {
              console.error('Error fetching artifacts:', error);
              return false;
            }
      - name: Run W1.yaml if artifact does not exist
        if: ${{steps.check_artifact.outputs.artifactExists}} == 'true'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const { data: workflows } = await github.actions.listRepoWorkflows({ owner: context.repo.owner, repo: context.repo.repo });
              console.log('Workflows:', workflows);
              const workflow = workflows.find(w => w.path === '.github/workflows/W1.yaml');
              console.log('Workflow:', workflow);
              if (workflow) {
                await github.actions.createWorkflowDispatch({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  workflow_id: workflow.id,
                });
              } else {
                console.error('Workflow not found.');
              }
            } catch (error) {
              console.error('Error finding workflow:', error);
            }
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: W1.yaml
          if_no_artifact_found: warn
      
      - name: List Files
        run: ls -R
