name: Workflow_2

on:
  workflow_run:
    workflows: ["Workflow_1"]
    types:
      - completed
env:
  OWNER: PulkitBindal
  NAME: GIT_Artifact_Logic
jobs:
  job-check-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Creating File Name
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "filename=steven-$git_hash.txt" >> $GITHUB_ENV
          
      - name: Check Artifact Existence
        id: check
        uses: xSAVIKx/artifact-exists-action@v0
        with:
          name: ${{ env.filename }}
      - name: Printing Results - Positive
        if: "${{ steps.check.outputs.exists == 'true' }}"
        run: echo "Artifact exists."
      - name: Printing Results - Negative
        if: "${{ steps.check.outputs.exists == 'false' }}"
        run: echo "Artifact didn`t exist."
        
      - name: Triggering Workflow_1 and Fetching Details
        id: art
        if: "${{ steps.check.outputs.exists == 'false' }}"
        run: |
          echo "Triggering Workflow_1 YAML File via API..."
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ARTIFACTLOGIC }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$OWNER/$NAME/actions/workflows/Workflow_1.yaml/dispatches -d '{"ref":"main"}'
          latest_artifact_name=$(curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ARTIFACTLOGIC }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$OWNER/$NAME/actions/artifacts | jq -r '.artifacts | sort_by(.created_at) | last | .name')
          latest_artifact_id=$(curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ARTIFACTLOGIC }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$OWNER/$NAME/actions/artifacts | jq -r '.artifacts | sort_by(.created_at) | last | .id')
          latest_run_id=$(curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.ARTIFACTLOGIC }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/$OWNER/$NAME/actions/runs | jq -r '.workflow_runs[0] | sort_by(.created_at) | last | .id')
          echo "LatestID=$latest_artifact_id" >> "$GITHUB_OUTPUT"
          echo "LatestName=$latest_artifact_name" >> "$GITHUB_OUTPUT"
          echo "LatestRunID=$latest_run_id" >> "$GITHUB_OUTPUT"
        shell: bash
  
      - name: Download build artifacts and Testing
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.filename }}
          github-token: ${{ secrets.ARTIFACTLOGIC }}
          repository: $OWNER/$NAME
          run-id: ${{ steps.art.outputs.LatestRunID}}

      - name: Validating the File
        run: ls -lrt
